= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.41.6...v0.41.7++[0.41.7^] (2021-03-26)

=== Continuous Integration

* enable Vagrant-based testing using GitHub Actions
(https://github.com/saltstack-formulas/postgres-formula/commit/2ebc9c11da512c8bc2089e8ecb28f5d3e13261f1[2ebc9c1^])
* *kitchen+ci:* use latest pre-salted images (after CVE) [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/cc43d1c90db36c232012bc80b66baa248ece3c42[cc43d1c^])

=== Documentation

* *readme:* add `Testing with Vagrant` section
(https://github.com/saltstack-formulas/postgres-formula/commit/ed2d6884b10725fad55b83de4972e59710f1970f[ed2d688^])

=== Tests

* standardise use of `share` suite & `_mapdata` state [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/fc53d977b32290834dc5aa17fe461154b269d38c[fc53d97^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.41.5...v0.41.6++[0.41.6^] (2021-02-26)

=== Bug Fixes

* *repo:* check whether pkg_repo is set
(https://github.com/saltstack-formulas/postgres-formula/commit/26b223323fa65abee731af04ee9631062a78b308[26b2233^])
* *repo:* reorder dependencies to prevent errors
(https://github.com/saltstack-formulas/postgres-formula/commit/750d8aab7a7e386e5ca0a3d546bb5cf12aa4506c[750d8aa^])

=== Continuous Integration

* *gemfile+lock:* use `ssf` customised `kitchen-docker` repo [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/476b15e326b72a6bbdb9635d612f30b7a51ce7fa[476b15e^])
* *kitchen+gitlab-ci:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/6f04b3191c6d1354d376473ff6e3ba213d614a4d[6f04b31^])
* *pre-commit:* update hook for `rubocop` [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/e964c26a29e61c5455b880e00195d5a0f55de641[e964c26^])

=== Tests

* *command_spec:* fix `rubocop` violation [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/73c39aff5ef9bf5808a251f70504e3b019087f01[73c39af^])
* *pillar:* update conditional to include Tumbleweed
(https://github.com/saltstack-formulas/postgres-formula/commit/e976ee9c9924363db400b23cbde914112b6b4349[e976ee9^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.41.4...v0.41.5++[0.41.5^] (2021-01-07)

=== Bug Fixes

* *cent7:* postgres11 needs libicu installed
(https://github.com/saltstack-formulas/postgres-formula/commit/4c0f796f00901b88e0ee9d778a5acb2115bf17cb[4c0f796^])

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/e84389dbb31f04f3eeabfd3935ef193e09e5b562[e84389d^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/2615411ec019600328c330cb4e72de89472f8fc9[2615411^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.41.3...v0.41.4++[0.41.4^] (2020-12-16)

=== Bug Fixes

* *archlinux:* avoid nonetype error
(https://github.com/saltstack-formulas/postgres-formula/commit/0a6cf8fefae1bbd5668a447ced911088ac965475[0a6cf8f^])
* *archlinux:* use consistent jinja repo check
(https://github.com/saltstack-formulas/postgres-formula/commit/3a955e02708b23929c93f879bcba0e3fe5ae5666[3a955e0^])
* *jinja:* syntax correction
(https://github.com/saltstack-formulas/postgres-formula/commit/8b44c068fcfd4199336596bdba095fc0e6c8fb2e[8b44c06^])
* *python:* use python3 postres on cent7/8
(https://github.com/saltstack-formulas/postgres-formula/commit/d6d1068395131de08534e387d377389bd078d3ee[d6d1068^])
* *suse:* version 11+ repo support on suse
(https://github.com/saltstack-formulas/postgres-formula/commit/b3f381e54750a00bb19a4aa50c6273c627dca16c[b3f381e^])

=== Continuous Integration

* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/postgres-formula/commit/a45673a87892deb973afee3689aea4bebd7a5739[a45673a^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/db1794b6bbb6ce183e5231cb4b7e7193dcb80143[db1794b^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/f04d60a773461dce98b4f2a7c8abbbab268513a0[f04d60a^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/7036f60e8ca3857beeca18abe70a3c59b6a021ec[7036f60^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.41.2...v0.41.3++[0.41.3^] (2020-09-29)

=== Bug Fixes

* *upstream:* require_in/require use_upstream
(https://github.com/saltstack-formulas/postgres-formula/commit/ab6b97e8c3ff40f9cb2e629c3c0faf09ca59ede9[ab6b97e^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.41.1...v0.41.2++[0.41.2^] (2020-07-27)

=== Bug Fixes

* *macros:* fix `format_kwargs` macro
(https://github.com/saltstack-formulas/postgres-formula/commit/5e6511b783388930010e6c0795b197728fb10b39[5e6511b^])

=== Continuous Integration

* *kitchen:* ubuntu-2004-master-py3 added
(https://github.com/saltstack-formulas/postgres-formula/commit/79789765439bb0727521dc817fe9eaebba000a67[7978976^])
* *kitchen+travis:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/702323c24df1df6b11defd663b55cf38586bd3f3[702323c^])
* *travis:* ubuntu upgrade from 16 to 18 & 20
(https://github.com/saltstack-formulas/postgres-formula/commit/44568a680602fb61f157b74dc05f9af9b153e8e6[44568a6^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/8735cf8ad1b9fc1eb816aecf3d363d4fc81fbe66[8735cf8^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.41.0...v0.41.1++[0.41.1^] (2020-07-10)

=== Bug Fixes

* *contributing:* postgresql-repo state ID requires python3-apt package
(https://github.com/saltstack-formulas/postgres-formula/commit/69b57e3b69062d0b66bd9fb28e3769a9ff579faa[69b57e3^])
* *contributing:* postgresql-service-reload type
(https://github.com/saltstack-formulas/postgres-formula/commit/278893c2f0f3fa8db26b45b3874f7dd7177b714a[278893c^])
* *contributing:* runnig formula inside container
(https://github.com/saltstack-formulas/postgres-formula/commit/68a791ef091114b081f71631d94201a9f1ed07b6[68a791e^])
* *libtofs:* “files_switch” mess up the variable exported by “map.jinja”
 [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/e6b14853d5ce2369ead22cabdfc48ae63f64e550[e6b1485^])
* *postgres.server:* reverted how posrgre.server.image is included
(https://github.com/saltstack-formulas/postgres-formula/commit/07044bf7c1d420855b43d6add30358ff39666702[07044bf^])

=== Continuous Integration

* *gemfile:* remove unused `rspec-retry` gem [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/85feac2852ee399f37293b60008e3a17d19cd47f[85feac2^])
* *gemfile:* update for Vagrant testing [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/061715e560880a9a60720bbcbeda632c010d03a4[061715e^])
* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/35850da22cb4f61144a61098b9869603b6e0a682[35850da^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/86697d8df48e24e37d6885f68ea8988d43b076aa[86697d8^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/5e29999495f36653aa1b51f2baf956533fdee7e4[5e29999^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/c46053abd8019a4229daf19db1af86c5f8961353[c46053a^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/442cfec245fb6b22d7768c8436ba6c62ca2975fd[442cfec^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/0c766c8e2e336e31d44fdddf5f4c5e56faa9e40e[0c766c8^])

=== Documentation

* *container:* "postgres:bake_image" specifics
(https://github.com/saltstack-formulas/postgres-formula/commit/904a5258cd155f3b5a83ec8dc8e990a8ffc6b798[904a525^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.40.5...v0.41.0++[0.41.0^] (2019-12-27)

=== Bug Fixes

* *mac_shortcut.sh:* fix `shellcheck` error
(https://github.com/saltstack-formulas/postgres-formula/commit/d538798ee4423ecb72b29bd39e4f35437412ce43[d538798^])
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/f3ec66d5ed90bc9a458fdff2233c9a707f0c9c72[f3ec66d^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/a77bb06b18823c7db0debd2c4ff135a367f76d04[a77bb06^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/20e5e46e1011641714a11756617530b898e3d689[20e5e46^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/8080be6be3dd0c8799fa102b1235fb151514bced[8080be6^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/8ce1ee4ecc5dd6a6a14118eda75b3446b6f58d82[8ce1ee4^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/bd5959c60a93e65ea0658f5cb7fd1609bdd3399c[bd5959c^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/0a2b63aba85b09c8983d066cbad7e344de791db1[0a2b63a^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/f0d12caac67bf7f2049ca7f1b7185912e876cb02[f0d12ca^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/1392538665bea2a699836a87a6b749e07276a94d[1392538^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/c9a57aa96bb80dc27c4722e0f8dc45c77460c03a[c9a57aa^])

=== Features

* *codenamemap:* update for current versions
(https://github.com/saltstack-formulas/postgres-formula/commit/9cc95c020909563486f404b186e15ed71dd8a83a[9cc95c0^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/ccaf4e5e3729c75c3a5eccbf482e7fca09415fea[ccaf4e5^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.40.4...v0.40.5++[0.40.5^] (2019-10-28)

=== Bug Fixes

* *macros.jinja:* apply suggestion from PR
(https://github.com/saltstack-formulas/postgres-formula/commit/d606b28[d606b28^])
* *macros.jinja:* use `user` kwarg for schemas (required on FreeBSD)
(https://github.com/saltstack-formulas/postgres-formula/commit/7ff798a[7ff798a^])

=== Continuous Integration

* *kitchen:* add pre-salted `FreeBSD-12.0` box for local testing
(https://github.com/saltstack-formulas/postgres-formula/commit/eefb89e[eefb89e^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/81b2c2e[81b2c2e^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/62baac2[62baac2^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/5a291ab[5a291ab^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/e568f28[e568f28^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.40.3...v0.40.4++[0.40.4^] (2019-10-11)

=== Bug Fixes

* *rubocop:* add fixes using `rubocop --safe-auto-correct`
(https://github.com/saltstack-formulas/postgres-formula/commit/37b0c43[37b0c43^])
* *rubocop:* fix remaining errors manually
(https://github.com/saltstack-formulas/postgres-formula/commit/b369aa9[b369aa9^])

=== Continuous Integration

* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/postgres-formula/commit/7822200[7822200^])
* *travis:* merge `rubocop` linter into main `lint` job
(https://github.com/saltstack-formulas/postgres-formula/commit/2c82872[2c82872^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.40.2...v0.40.3++[0.40.3^] (2019-10-10)

=== Bug Fixes

* *manage.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/postgres-formula/commit/bf5b4d6[bf5b4d6^])
* *python.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/postgres-formula/commit/1f3cfcc[1f3cfcc^])

=== Continuous Integration

* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/postgres-formula/commit/7ca61f3[7ca61f3^])
* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/76e3e39[76e3e39^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/3a27978[3a27978^])
* *platform:* add `arch-base-latest` (commented out for now) [skip ci]
(https://github.com/saltstack-formulas/postgres-formula/commit/89e4a34[89e4a34^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/postgres-formula/commit/a0fdd48[a0fdd48^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.40.1...v0.40.2++[0.40.2^] (2019-09-13)

=== Bug Fixes

* *freebsd:* no libpqdev freebsd package
(https://github.com/saltstack-formulas/postgres-formula/commit/eca6d97[eca6d97^])

=== Continuous Integration

* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/postgres-formula/commit/9796319[9796319^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.40.0...v0.40.1++[0.40.1^] (2019-09-11)

=== Continuous Integration

* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/postgres-formula/commit/fc6cbe0[fc6cbe0^])

=== Documentation

* *pillar.example:* update examples for freebsd
(https://github.com/saltstack-formulas/postgres-formula/commit/a799214[a799214^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.39.1...v0.40.0++[0.40.0^] (2019-09-03)

=== Features

* *archlinux:* add support, fixing rendering errors
(https://github.com/saltstack-formulas/postgres-formula/commit/e970925[e970925^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.39.0...v0.39.1++[0.39.1^] (2019-09-01)

=== Continuous Integration

* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/postgres-formula/commit/140928b[140928b^])

=== Tests

* *inspec:* fix reference to `suse` after gem `train` update
(https://github.com/saltstack-formulas/postgres-formula/commit/677adba[677adba^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.38.0...v0.39.0++[0.39.0^] (2019-08-17)

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/postgres-formula/commit/1f0fd92[1f0fd92^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.37.4...v0.38.0++[0.38.0^] (2019-07-24)

=== Continuous Integration

* *kitchen:* remove `python*-pip` installation
(https://github.com/saltstack-formulas/postgres-formula/commit/d999597[d999597^])
* *kitchen+travis:* modify matrix to include `develop` platform
(https://github.com/saltstack-formulas/postgres-formula/commit/3f81439[3f81439^])

=== Features

* *debian:* add buster support
(https://github.com/saltstack-formulas/postgres-formula/commit/904ba27[904ba27^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.37.3...v0.37.4++[0.37.4^] (2019-05-31)

=== Continuous Integration

* *travis:* reduce matrix down to 6 instances
(https://github.com/saltstack-formulas/postgres-formula/commit/2ff919f[2ff919f^])

=== Tests

* *``services_spec``:* remove temporary `suse` conditional
(https://github.com/saltstack-formulas/postgres-formula/commit/81165fc[81165fc^])
* *command_spec:* use cleaner `match` string using `%r`
(https://github.com/saltstack-formulas/postgres-formula/commit/a054cea[a054cea^])
* *locale:* improve test using locale `en_US.UTF-8`
(https://github.com/saltstack-formulas/postgres-formula/commit/7796064[7796064^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.37.2...v0.37.3++[0.37.3^] (2019-05-16)

=== Bug Fixes

* *freebsd-user:* fix FreeBSD daemon's user for PostgreSQL >= 9.6
(https://github.com/saltstack-formulas/postgres-formula/commit/8745365[8745365^]),
closes
https://github.com/saltstack-formulas/postgres-formula/issues/263[#263^]

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.37.1...v0.37.2++[0.37.2^] (2019-05-12)

=== Bug Fixes

* *sysrc-svc:* workaround *BSD minion indefinitely hanging on start
(https://github.com/saltstack-formulas/postgres-formula/commit/0aa8b4a[0aa8b4a^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.37.0...v0.37.1++[0.37.1^] (2019-05-06)

=== Documentation

* *readme:* fix link for Travis badge
(https://github.com/saltstack-formulas/postgres-formula/commit/850ca6a[850ca6a^])

== link:++https://github.com/saltstack-formulas/postgres-formula/compare/v0.36.0...v0.37.0++[0.37.0^] (2019-05-06)

=== Code Refactoring

* *kitchen:* prefer `kitchen.yml` to `.kitchen.yml`
(https://github.com/saltstack-formulas/postgres-formula/commit/8f7cbde[8f7cbde^])

=== Continuous Integration

* *gemfile:* prepare for `inspec` testing
(https://github.com/saltstack-formulas/postgres-formula/commit/157e169[157e169^])
* *kitchen:* use pre-salted images as used in `template-formula`
(https://github.com/saltstack-formulas/postgres-formula/commit/611ec11[611ec11^])
* *kitchen+travis:* use newly available pre-salted images
(https://github.com/saltstack-formulas/postgres-formula/commit/7b7aadc[7b7aadc^])
* *pillar_from_files:* use custom pillar based on `pillar.example`
(https://github.com/saltstack-formulas/postgres-formula/commit/c64d9e4[c64d9e4^])
* *travis:* add `.travis.yml` based on `template-formula`
(https://github.com/saltstack-formulas/postgres-formula/commit/6467df7[6467df7^])

=== Documentation

* *readme:* update `Testing` section for `inspec`
(https://github.com/saltstack-formulas/postgres-formula/commit/4cfde8d[4cfde8d^])

=== Features

* implement `semantic-release`
(https://github.com/saltstack-formulas/postgres-formula/commit/7d3aa19[7d3aa19^])

=== Tests

* *inspec:* add tests for multiple ports and postgres versions
(https://github.com/saltstack-formulas/postgres-formula/commit/bf6a653[bf6a653^])
* *inspec:* enable `use_upstream_repo` for `debian` & `centos-6`
(https://github.com/saltstack-formulas/postgres-formula/commit/49fdd33[49fdd33^])
* *inspec:* replace `serverspec` with `inspec` tests
(https://github.com/saltstack-formulas/postgres-formula/commit/58ac122[58ac122^])
* *inspec:* use relaxed command output match for the time being
(https://github.com/saltstack-formulas/postgres-formula/commit/3c53684[3c53684^])
